name: Terraform Deploy Pipeline

on:
  push:
    branches:
      - main
      - feature

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Azure Login (Service Principal se)
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURESECRET }}

      # Step 3: Setup Terraform
      - name: Installation Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.8.5

      # Step 4: Terraform Init
      - name: Terraform Init
        working-directory: ./env/prod
        run: terraform init

      # Step 5: Terraform Validate
      - name: Terraform Validate
        working-directory: ./env/prod
        run: terraform validate

      # Step 6: Terraform Plan
      - name: Terraform Plan
        working-directory: ./env/prod
        run: terraform plan -out=tfplan
